apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapp
  labels:
    app: coreapp
spec:
  selector:
    matchLabels:
      app: coreapp
  replicas: 2
  template:
    metadata:
      labels:
        app: coreapp
    spec:
      containers:
      - name: coreapp
        image: acrforaksdemo.azurecr.io/sandeepanumula92/coreapp
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: dotnetapp-port
---
apiVersion: v1
kind: Service
metadata:
  name: coreapp-service
  labels:
    app: coreapp
spec:
  ports:
  - port: 80
    targetPort: dotnetapp-port
  selector:
    app: coreapp
  type: LoadBalancer
